# Generated by Django 2.2.7 on 2019-11-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='hotline',
        ),
    ]
