# Generated by Django 2.2.7 on 2019-11-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191111_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'toys'), ('G', 'gift'), ('E', 'electric'), ('H', 'household'), ('F', 'furniture'), ('S', 'stationary'), ('B', 'bicycle')], max_length=1),
        ),
    ]
